---
title: "test"
author: "AN DoYeon"
date: '2019 10 29 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment=NA)
```

# Movie Score Prediction


## 1. 데이터 확인
```{r}
USA_movie <- read.csv("USA_movie.csv")
movie <- USA_movie
str(movie)
summary(movie)

```

## 2. 데이터 전처리

### 결측치 처리 => 평균으로 대치
```{r}
sum(is.na(movie))
1334 / (3807*28)

```

```{r}
avg_num_critic_for_reviews <- mean(movie$num_critic_for_reviews, na.rm = T)
movie$num_critic_for_reviews <- ifelse(is.na(movie$num_critic_for_reviews),
                                       avg_num_critic_for_reviews,movie$num_critic_for_reviews)

avg_duration <- mean(movie$duration, na.rm = T)
movie$duration <- ifelse(is.na(movie$duration), avg_duration, movie$duration)

avg_director_facebook_likes <- mean(movie$director_facebook_likes, na.rm = T)
movie$director_facebook_likes <- ifelse(is.na(movie$director_facebook_likes),
                                        avg_director_facebook_likes, movie$director_facebook_likes)

avg_actor_3_facebook_likes <- mean(movie$actor_3_facebook_likes, na.rm = T)                                      
movie$actor_3_facebook_likes <- ifelse(is.na(movie$actor_3_facebook_likes),
                                       avg_actor_3_facebook_likes, movie$actor_3_facebook_likes)

avg_actor_1_facebook_likes <- mean(movie$actor_1_facebook_likes, na.rm = T)
movie$actor_1_facebook_likes <- ifelse(is.na(movie$actor_1_facebook_likes),
                                       avg_actor_1_facebook_likes, movie$actor_1_facebook_likes)

avg_gross <- mean(movie$gross, na.rm = T)
movie$gross <- ifelse(is.na(movie$gross), avg_gross, movie$gross)

avg_facenumber_in_poster <- mean(movie$facenumber_in_poster, na.rm = T)
movie$facenumber_in_poster <- ifelse(is.na(movie$facenumber_in_poster),
                                     avg_facenumber_in_poster, movie$facenumber_in_poster)

avg_num_user_for_reviews <- mean(movie$num_user_for_reviews, na.rm = T)
movie$num_user_for_reviews <- ifelse(is.na(movie$num_user_for_reviews), 
                                     avg_num_user_for_reviews, movie$num_user_for_reviews)

avg_budget <- mean(movie$budget, na.rm = T)
movie$budget <- ifelse(is.na(movie$budget), avg_budget, movie$budget)


avg_actor_2_facebook_likes <- mean(movie$actor_2_facebook_likes, na.rm = T)
movie$actor_2_facebook_likes <- ifelse(is.na(movie$actor_2_facebook_likes), 
                                       avg_actor_2_facebook_likes, movie$actor_2_facebook_likes)

avg_aspect_ratio <- mean(movie$aspect_ratio, na.rm = T)
movie$aspect_ratio <- ifelse(is.na(movie$aspect_ratio), avg_aspect_ratio, movie$aspect_ratio)

```




## 3. 상관 관계 파악
### 1) IMDB 분포도
```{r}
library(ggplot2)
ggplot(data = movie, mapping = aes(x = imdb_score)) +
  geom_bar(fill = "#FFCC00") +
  theme_light()

```


### 2) Correlation Heatmap
 변수들 간의 상관 관계 파악


 숫자형이고, 의미 있는 변수들로만 이루어진 데이터 프레임 생성
 
```{r}
movie_data <- movie[c("num_critic_for_reviews", "duration", "director_facebook_likes",
                      "actor_3_facebook_likes", "actor_1_facebook_likes", "gross", "num_voted_users",
                      "cast_total_facebook_likes", "facenumber_in_poster", "num_user_for_reviews",
                      "budget", "actor_2_facebook_likes","imdb_score", "movie_facebook_likes")]


# 변수 수정 및 삭제
movie_data$other_actors_facebook_likes <- movie_data$actor_2_facebook_likes + movie_data$actor_3_facebook_likes
movie_data <- subset(movie_data, select = -c(cast_total_facebook_likes, actor_2_facebook_likes, actor_3_facebook_likes))

```


 Correlation Heatmap

```{r}
cormat <- round(cor(movie_data), 2)
head(cormat)

search()

library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)


# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}


reorder_cormat <- function(cormat){
  # Use correlation between variables as distance
  dd <- as.dist((1-cormat)/2)
  hc <- hclust(dd)
  cormat <-cormat[hc$order, hc$order]
}

# Reorder the correlation matrix
cormat <- reorder_cormat(cormat)
upper_tri <- get_upper_tri(cormat)
# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Create a ggheatmap
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
  ggtitle("Correlation Heatmap") +
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "black", high = "#FFCC00", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Movie\nCorrelation") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 10, hjust = 1),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0.5))+
  coord_fixed()
# Print the heatmap
print(ggheatmap)

```


### 3) IMDB score와 관련 있는 변수들로 이루어진 데이터 프레임 생성
```{r}
movie <- movie_data[c("facenumber_in_poster", "director_facebook_likes", "duration", "imdb_score",
                      "actor_1_facebook_likes", "other_actors_facebook_likes", "movie_facebook_likes",
                      "budget")]

```




## 4. 머신러닝

### 1) 다중 선형 회귀(Multiple Linear Regression)
```{r}
# 다중 선형 회귀
# 종속 변수 - imdb_score

# imdb_score 분포도
hist(movie$imdb_score, col = "#FFCC00", border = "white")


library(psych)
# 산점 행렬도
pairs.panels(movie)

library(car)
# 다중공선성 확인
# 다중공선성: 독립변수들이 서로 높은 상관관계를 가지면 회귀계수의 정확한 추정이 어렵다.
vif(lm(imdb_score ~ ., data = movie))
# vif 값은 보통 4가 넘으면 다중공선성이 존재한다고 본다.

```

=> 다중공선성 존재하지 않음

```{r}
# 회귀 모델
mov_model <- lm(formula = imdb_score ~ ., data = movie)

# 통계적으로 유의한지 여부 확인
summary(mov_model)   

# other_actors_facebook_likes 제외 나머지 변수들 유의미
# 모형 선택법(Model Selection) --> 유의하지 않은 변수 제거
# Backward selection
out <- lm(imdb_score ~., movie)
mov_model2 <- step(out, direction = "backward", trace = T)
summary(mov_model2)

plot(mov_model2)  # 모델이 적합한지


```

=> 이상치가 많음


### 2) 회귀 트리
```{r}
library(rpart)

sample_count <- round(nrow(movie)) * 0.75
set.seed(123)
sample_rows <- sample(nrow(movie), sample_count)

train <- movie[sample_rows, ]
test <- movie[-sample_rows, ]

# rpart를 이용해 학습시키기
movie_rpart <- rpart(formula = imdb_score ~ ., data = train)
movie_rpart

# 회귀트리 시각화
library(rpart.plot)
rpart.plot(x = movie_rpart, digits = 3, cex = 0.8, fallen.leaves = T, type = 5)

# 모델 평가
movie_predict <- predict(movie_rpart, test)
summary(movie_predict)
summary(test$imdb_score)

# 모델 성능 평가
# 1) 상관 계수
cor(movie_predict, test$imdb_score)   # 0.45
# 2) MAE: 평균 절대 오차
MAE <- function(actual, predict) {
  return(mean(abs(actual - predict)))
}
MAE(actual = test$imdb_score, predict = movie_predict)    # 0.76

```


### 3) 모델 트리
```{r}
# 모델 성능 향상
library(Cubist)
str(movie)
# 모델 트리
movie_cubist <- cubist(x = movie[-4], y = movie$imdb_score)
movie_cubist
summary(movie_cubist)

# 성능 테스트
movie_predict2 <- predict(movie_cubist, test)
head(movie_predict2)

summary(movie_predict2)
summary(movie$imdb_score)

# 상관계수
cor(movie_predict2, test$imdb_score)  # 0.55
# MAE
MAE(movie_predict2, test$imdb_score)  # 0.68

```

=> 상관계수는 0.1 높아졌고, MAE는 0.8 낮아짐
=> 성능 향상


### 4) 랜덤 포레스트(Random Forest Classification)
```{r}
library(randomForest)

set.seed(123)
mov_model3 <- randomForest(imdb_score ~ ., data = movie, importance = T)
print(mov_model3)

importance(mov_model3)
varImpPlot(mov_model3)
```

